name: publish www

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Set up Nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generating API docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Build headless-demo
        run: ./gradlew headless-demo:build

      - name: Build Webpage
        working-directory: ./www
        run: npm install && npm run build

      - name: Copy api docs to webpage
        run: mkdir -p ./www/_site/api && cp -r ./api/* ./www/_site/api

      - name: Copy headless-demo files to webpage
        run: mkdir -p ./www/_site/headless-demo && cp ./headless-demo/build/distributions/* ./www/_site/headless-demo

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          jekyll: false
          fqdn: next.fritz2.dev
          build_dir: ./www/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}